[package]
name = "svart"
version = "1.0.0"
edition = "2021"

[dependencies]
# Use Cozy-Chess for move-gen and board representation
cozy-chess = "0.3.1"

[profile.release]
lto = "fat"
codegen-units = 1
