[package]
name = "Daedalus"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Use Cozy-Chess PEXT
cozy-chess = "0.3.1"
