[package]
name = "daedalus"
version = "0.4.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Use Cozy-Chess for move-gen and board representation
cozy-chess = "0.3.1"
